### ISSUE TITLE
OctoBTT does not coexist with Klipper

### ISSUE THREAD

**Issue by top-gun** [bigtreetech/OctoBTT#3]
I have used OctoBTT for about a month, and have just migrated my Ender with BTT Mini E3 1.2 from Marlin to Klipper. When OctoBTT is active, OctoPrint is unable to connect to Klipper's virtual printer /tmp/printer. Octoprint seems to be forced to connect to /dev/tty/ACM0. I have changed the Octoprint setting for the default printer to /tmp/printer, but this is ignored.

When I kill OctoBTT, Octoprint can immediately connect to /tmp/printer.

I disabled the autostart of OctoBTT, and Klipper is now running fine with Octoprint.

**Comment by bigtreetech** [comment]
Since OctoPrint's serial port connection has a long waiting time, which affects the efficiency of the hot connection, the mode of forced USB connection is adopted at present. The current problems will not be formally perfected until reasonable and efficient schemes are available in the future; I am very sorry for the problem you brought. I will record the problem and speed up the implementation of the plan. Please look forward to the future version.

If you want to use Klipper in OctoBTT, you can recompile OctoBTT by changing the **"OctoBTT/octonetwork.h"** on line 49 in the source file **"const QList<QString> ConnectSerialLink = {"/dev/ttyAMA0","/dev/ttyS0"};"** to **"const QList<QString> ConnectSerialLink = {};"**; However, this code is not recommended for non-Klipper connections, as it causes the OctoBTT interface to be terribly stuck.
