### ISSUE TITLE
Camera icon does not work

### ISSUE THREAD

**Issue by Poppy45** [bigtreetech/OctoBTT#4]
When pressing the camera icon opens a blank page .can see camera output on web page of Octoprint. Any help

**Comment by skinz98** [comment]
Having the same problem

**Comment by Shine6Z** [comment]
Thank you for your exploration. As I am still testing this section, it will not be online for the time being, and these functions will be put online one after another after it becomes stable.

**Comment by byseven07** [comment]
Same issue !!!

**Comment by 3dbret** [comment]
this does not work for me too, it does nothing.

**Comment by bigtreetech** [comment]
Until now, the rendering code of video stream cannot work properly, so this meaningless code fragment cannot be opened to users for the time being. In the latest update, I will close this entry until the problem is completely solved and it will be opened to users again. I am very sorry for the misunderstanding caused by everyone.

**Comment by bigtreetech** [comment]
Thanks for waiting, now Octoprint's previews are supported and you're welcome to try out the new feature.
