### ISSUE TITLE
WIFI menu/config doesnt work

### ISSUE THREAD

**Issue by jranger615** [bigtreetech/OctoBTT#5]
Wifi doesnt work via file with google mesh. If i goto the config menu in the gui i see nothing and it freezes. Cannot exit wifi menu

**Comment by Shine6Z** [comment]
The interface freeze is mainly caused by the slowness of the system in obtaining available WiFi devices in the background. The interface can only be automatically lifted after obtaining the list of devices. For this problem, I will keep looking for more efficient solutions.As for Google mesh, I don't know your Google mesh WiFi frequencies, which working in most raspberry pie are working in 2.4 G WiFi frequencies, in addition to Pi4B built-in WiFi devices can work at 5 G band, so need to make sure your raspberry pie with which version or raspberries pie with WiFi module is to support those frequencies, depending on your trial is a built-in or extra, if the WiFi module, also need to know whether module on the raspberry pie need to install additional drivers,Not all modules can be applied directly to the raspberry pie.
