### ISSUE TITLE
Wifi not working with the Screen Connected

### ISSUE THREAD

**Issue by fenix8k** [bigtreetech/OctoBTT#8]
I just get the new BIGTREETECH PI TFT50 V1.0 TFT-display, it work really well, buuuut, when I have it attached to a Raspberry Pi 4 with the mounting screws, the Wifi drops or work really bad, if I detach the Screen from the Pi (still attached to the pi via the cable), the Wifi start working Again, any sugestión?, I read that HDMI signal can interfiere with 2G and 5G networks this can explain this behavior.

Thx!

**Comment by xan105** [comment]
I received my display yesterday. Wifi of my rpi4 is dead when screwed to the back plate. As soon as I unscrewed it the wifi is back. 
You are not alone with this issue.

**Comment by bigtreetech** [comment]
The question is under confirmation, please wait patiently, and we will reply in two weeks.

**Comment by Shine6Z** [comment]
We passed the preliminary check problem for Raspberry Pi 4 Model B Wifi problems, Raspberry Pi 4 Model B antenna radiation direction to the main board PCB back, when the PCB back a valid GND can form shielding effect of antenna, leading to insufficient antenna performance and the disturbance, the current solution is to use 17.5 mm high column screw to hold down the blackberry pie motherboard and the spacing between the screen, so that antenna radiation reserve enough space, can work stable.

**Comment by NovaViper** [comment]
I'm having the same issue on both my raspberry pi 3B+ and Pi 4 2GB, will this be fixed????

**Comment by Acidice1000** [comment]
Pi4 with pi tft 50 v2. The moment the ribbon cable is plugged in the pi does not connect with wifi. Used a 2m cable and still it is not working. Tried with pi 3 and same issue. Problem is definitely not fixed.

**Comment by hoonu** [comment]
Thanks for the heads up. I was trying to decide between the Pi 7" and this screen and it seems this might just be the deciding factor. I wonder if they just have some lcds out there that spew more EMI than others and that's why this issue isn't as widespread.

**Comment by Hemmertyme** [comment]
I just returned my TFT35 v3.0 because it wouldn’t work with Klipper.   I didn’t return my SKR mini E3 because I had hopes for another option.  So I decided to order the TFT50 as a screen for my pi.  It arrived and now this damn thing doesn’t work either.  I have wasted sooo much time dealing with BTT’s shoddy products.  Unless I get some resolve I’m done with their products.
